spring:
  config:
    activate:
      on-profile: test
  flyway:
    enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:15.3:///ml_recommendation_svc_test
    username: ml_recommendation_svc_test
    password: dba