/**
 * Initial DDL
 */
-- countries
CREATE TABLE countries
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version      BIGINT,
    date_created TIMESTAMP WITH TIME ZONE                NOT NULL,
    last_updated TIMESTAMP WITH TIME ZONE                NOT NULL,
    name         VARCHAR(255),
    CONSTRAINT pk_countries PRIMARY KEY (id)
);

ALTER TABLE countries
    ADD CONSTRAINT uc_countries_name UNIQUE (name);

-- states
CREATE TABLE states
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version      BIGINT,
    date_created TIMESTAMP WITH TIME ZONE                NOT NULL,
    last_updated TIMESTAMP WITH TIME ZONE                NOT NULL,
    name         VARCHAR(255),
    country_id   BIGINT,
    CONSTRAINT pk_states PRIMARY KEY (id)
);

ALTER TABLE states
    ADD CONSTRAINT uc_states_name UNIQUE (name);

ALTER TABLE states
    ADD CONSTRAINT FK_STATES_ON_COUNTRY FOREIGN KEY (country_id) REFERENCES countries (id);

-- cities
CREATE TABLE cities
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version      BIGINT,
    date_created TIMESTAMP WITH TIME ZONE                NOT NULL,
    last_updated TIMESTAMP WITH TIME ZONE                NOT NULL,
    name         VARCHAR(255),
    state_id     BIGINT,
    CONSTRAINT pk_cities PRIMARY KEY (id)
);

ALTER TABLE cities
    ADD CONSTRAINT uc_cities_name UNIQUE (name);

ALTER TABLE cities
    ADD CONSTRAINT FK_CITIES_ON_STATE FOREIGN KEY (state_id) REFERENCES states (id);
